// const withTM = require('next-transpile-modules')(['react-firebaseui']);

module.exports = (mode) => ({
  reactStrictMode: true,
  // env: {
  //   NEXT_PUBLIC_API_ENDPOINT: process.env.NEXT_PUBLIC_API_ENDPOINT,
  //   NEXT_PUBLIC_FIREBASE_KEY: process.env.NEXT_PUBLIC_FIREBASE_KEY,
  //   NEXT_PUBLIC_FIREBASE_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_DOMAIN,
  //   NEXT_PUBLIC_FIREBASE_PROJECT_ID:
  //     process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  //   NEXT_PUBLIC_FIREBASE_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  //   NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:
  //     process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  //   NEXT_PUBLIC_FIREBASE_DATBASE_URL:
  //     process.env.NEXT_PUBLIC_FIREBASE_DATBASE_URL,
  //   NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:
  //     process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  //   NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID:
  //     process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
  //   NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  // },
});
