name: production deploy
on:
  push:
    branches:
      - main
env:
  # SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  PORT: ${{ secrets.PORT }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  IMAGE: gcr.io/dation/dation-client

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'
      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "::set-output name=dir::$(yarn cache dir)"
      # - name: Cache dependencies
      #   uses: actions/cache@v2
      #   with:
      #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn run test
      - name: Deploy
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: $GCP_PROJECT_ID
          service_account_key: $SERVICE_ACCOUNT_KEY
          export_default_credentials: true
      - name: Configure docker
        run: gcloud auth configure-docker --quiet
      - name:  Build dockerfile
        run: docker build -t $IMAGE .
      - name: Push docker image
        run: docker push $IMAGE
      - name: deploy to cloud run
        run: |
          gcloud run deploy dation-client \
            --image $IMAGE \
            --project $GCP_PROJECT_ID \
            --port $PORT \
            --region $GCP_REGION \
            --platform managed \
            --quiet